name: manipulate secrets
run-name: read secrets from repo config
on: push
jobs:
  read-env:
    runs-on: ubuntu-latest
    environment: staging
    envs:
      - name: PROCESS
        value: staging
    steps:
      - run: echo ${{ ACCESS_TOKEN }}
      - run: echo ${{ GENERAL_TOKEN }}
