name: manipulate secrets
run-name: read secrets from repo config
on: push
env: |
  PROCESS=staging
jobs:
  read-env:
    runs-on: ubuntu-latest
    environment: staging
    steps:
      - run: echo ${{ secrets.ACCESS_TOKEN }}
      - run: echo ${{ secrets.GENERAL_TOKEN }}
      - run: echo ${{ env.PROCESS }}
