name: manipulate secrets
run-name: read secrets from repo config
on: push
jobs:
  read-env:
    runs-on: ubuntu-latest
    environment: staging
    env:
      - PROCESS: staging
    steps:
      - run: echo ${{ secrets.ACCESS_TOKEN }}
      - run: echo ${{ secrets.GENERAL_TOKEN }}
      - run: echo ${{ env.PROCESS }}
